# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The blog of MCT
email: mct-info@imv.uio.no
description: >- # this means to ignore newlines until "baseurl:"
  This is the blog of the Music, Communication & Technology (MCT) joint Master's programme between NTNU and UiO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mct-master.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MCT_master
github_username:  MCT-master
google_analytics: 'UA-131306863-1'
# Comments
comments:
  provider: disqus
disqus:
  shortname: https-mct-master-github-io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
